package com.ymatou.autorun.datadriver.base.database.model;
public class Stc_CaseData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.CaseId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.UserId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.Model
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.SceneId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private Integer sceneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.Scene
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String scene;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_scene.Scene_host
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String Scene_host;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_scene.Scene_api
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String Scene_api;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.CaseDescription
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String caseDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.CheckPoint
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String checkPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.TemplateId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.TemplateName
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.TemplateDetail
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String TemplateDetail;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_template.ExtraInputList
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String extraInputList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.DefautCheckType
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private Integer defautCheckType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_template.input2SqlMap
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String input2SqlMap;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_template.sql2MongoMap
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String sql2MongoMap;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_template.output2SqlMap
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String output2SqlMap;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_template.output2MongoMap
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String output2MongoMap;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stc_case.extraCheckList
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    private String extraCheckList;



    public String getTemplateDetail() {
		return TemplateDetail;
	}


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.CaseId
     *
     * @param caseId the value for stc_case.CaseId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.UserId
     *
     * @return the value of stc_case.UserId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.UserId
     *
     * @param userId the value for stc_case.UserId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.Model
     *
     * @return the value of stc_case.Model
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.Model
     *
     * @param model the value for stc_case.Model
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.SceneId
     *
     * @return the value of stc_case.SceneId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public Integer getSceneId() {
        return sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.SceneId
     *
     * @param sceneId the value for stc_case.SceneId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.Scene
     *
     * @return the value of stc_case.Scene
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public String getScene() {
        return scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.Scene
     *
     * @param scene the value for stc_case.Scene
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setScene(String scene) {
        this.scene = scene == null ? null : scene.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.CaseDescription
     *
     * @return the value of stc_case.CaseDescription
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public String getCaseDescription() {
        return caseDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.CaseDescription
     *
     * @param caseDescription the value for stc_case.CaseDescription
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setCaseDescription(String caseDescription) {
        this.caseDescription = caseDescription == null ? null : caseDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.CheckPoint
     *
     * @return the value of stc_case.CheckPoint
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public String getCheckPoint() {
        return checkPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.CheckPoint
     *
     * @param checkPoint the value for stc_case.CheckPoint
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setCheckPoint(String checkPoint) {
        this.checkPoint = checkPoint == null ? null : checkPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.TemplateId
     *
     * @return the value of stc_case.TemplateId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.TemplateId
     *
     * @param templateId the value for stc_case.TemplateId
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.TemplateName
     *
     * @return the value of stc_case.TemplateName
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.TemplateName
     *
     * @param templateName the value for stc_case.TemplateName
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.ExtraInputList
     *
     * @return the value of stc_case.ExtraInputList
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public String getExtraInputList() {
        return extraInputList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.ExtraInputList
     *
     * @param extraInputList the value for stc_case.ExtraInputList
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setExtraInputList(String extraInputList) {
        this.extraInputList = extraInputList == null ? null : extraInputList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.DefautCheckType
     *
     * @return the value of stc_case.DefautCheckType
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public Integer getDefautCheckType() {
        return defautCheckType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.DefautCheckType
     *
     * @param defautCheckType the value for stc_case.DefautCheckType
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setDefautCheckType(Integer defautCheckType) {
        this.defautCheckType = defautCheckType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stc_case.ExtraCheckList
     *
     * @return the value of stc_case.ExtraCheckList
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public String getExtraCheckList() {
        return extraCheckList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stc_case.ExtraCheckList
     *
     * @param extraCheckList the value for stc_case.ExtraCheckList
     *
     * @mbggenerated Tue Nov 15 20:13:15 CST 2016
     */
    public void setExtraCheckList(String extraCheckList) {
        this.extraCheckList = extraCheckList == null ? null : extraCheckList.trim();
    }
    
    public String getScene_host() {
		return Scene_host;
	}

	public void setScene_host(String scene_host) {
		Scene_host = scene_host;
	}

	public String getScene_api() {
		return Scene_api;
	}

	public void setScene_api(String scene_api) {
		Scene_api = scene_api;
	}

	public void setTemplateDetail(String templateDetail) {
		TemplateDetail = templateDetail;
	}

	public String getInput2SqlMap() {
		return input2SqlMap;
	}

	public void setInput2SqlMap(String input2SqlMap) {
		this.input2SqlMap = input2SqlMap;
	}

	public String getSql2MongoMap() {
		return sql2MongoMap;
	}

	public void setSql2MongoMap(String sql2MongoMap) {
		this.sql2MongoMap = sql2MongoMap;
	}

	public String getOutput2SqlMap() {
		return output2SqlMap;
	}

	public void setOutput2SqlMap(String output2SqlMap) {
		this.output2SqlMap = output2SqlMap;
	}

	public String getOutput2MongoMap() {
		return output2MongoMap;
	}

	public void setOutput2MongoMap(String output2MongoMap) {
		this.output2MongoMap = output2MongoMap;
	}

	public Integer getCaseId() {
        return caseId;
    }

}