package  com.ymatou.autorun.datadriver.base.autoresult.database.Bean;

public class ResultContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultcontent.id
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultcontent.createtime
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultcontent.del
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultcontent.status
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultcontent.type
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultcontent.testcaseresultid
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    private Integer testcaseresultid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultcontent.content
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultcontent.id
     *
     * @return the value of resultcontent.id
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultcontent.id
     *
     * @param id the value for resultcontent.id
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultcontent.createtime
     *
     * @return the value of resultcontent.createtime
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultcontent.createtime
     *
     * @param createtime the value for resultcontent.createtime
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultcontent.del
     *
     * @return the value of resultcontent.del
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultcontent.del
     *
     * @param del the value for resultcontent.del
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultcontent.status
     *
     * @return the value of resultcontent.status
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultcontent.status
     *
     * @param status the value for resultcontent.status
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultcontent.type
     *
     * @return the value of resultcontent.type
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultcontent.type
     *
     * @param type the value for resultcontent.type
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultcontent.testcaseresultid
     *
     * @return the value of resultcontent.testcaseresultid
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public Integer getTestcaseresultid() {
        return testcaseresultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultcontent.testcaseresultid
     *
     * @param testcaseresultid the value for resultcontent.testcaseresultid
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public void setTestcaseresultid(Integer testcaseresultid) {
        this.testcaseresultid = testcaseresultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultcontent.content
     *
     * @return the value of resultcontent.content
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultcontent.content
     *
     * @param content the value for resultcontent.content
     *
     * @mbggenerated Wed Feb 24 18:27:28 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}