package  com.ymatou.autorun.datadriver.base.autoresult.database.Bean;

public class TestSuite{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuite.id
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuite.createtime
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuite.del
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuite.updatetime
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuite.url
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuite.applicationid
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    private Integer applicationid;
    private String description;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuite.id
     *
     * @return the value of testsuite.id
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    
    public Integer getId() {
        return id;
    }

    public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuite.id
     *
     * @param id the value for testsuite.id
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuite.createtime
     *
     * @return the value of testsuite.createtime
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuite.createtime
     *
     * @param createtime the value for testsuite.createtime
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuite.del
     *
     * @return the value of testsuite.del
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuite.del
     *
     * @param del the value for testsuite.del
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuite.updatetime
     *
     * @return the value of testsuite.updatetime
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuite.updatetime
     *
     * @param updatetime the value for testsuite.updatetime
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuite.url
     *
     * @return the value of testsuite.url
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuite.url
     *
     * @param url the value for testsuite.url
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuite.applicationid
     *
     * @return the value of testsuite.applicationid
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public Integer getApplicationid() {
        return applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuite.applicationid
     *
     * @param applicationid the value for testsuite.applicationid
     *
     * @mbggenerated Wed Feb 24 18:28:47 CST 2016
     */
    public void setApplicationid(Integer applicationid) {
        this.applicationid = applicationid;
    }
}