package  com.ymatou.autorun.datadriver.base.autoresult.database.Bean;

public class TestCase {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column testcase.id
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column testcase.createtime
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	private String createtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column testcase.del
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	private Integer del;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column testcase.description
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column testcase.name
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column testcase.updatetime
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	private String updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column testcase.testsuiteid
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	private Integer testsuiteid;
	private String type;

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column testcase.id
	 *
	 * @return the value of testcase.id
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column testcase.id
	 *
	 * @param id
	 *            the value for testcase.id
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column testcase.createtime
	 *
	 * @return the value of testcase.createtime
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public String getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column testcase.createtime
	 *
	 * @param createtime
	 *            the value for testcase.createtime
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public void setCreatetime(String createtime) {
		this.createtime = createtime == null ? null : createtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column testcase.del
	 *
	 * @return the value of testcase.del
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public Integer getDel() {
		return del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column testcase.del
	 *
	 * @param del
	 *            the value for testcase.del
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public void setDel(Integer del) {
		this.del = del;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column testcase.description
	 *
	 * @return the value of testcase.description
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column testcase.description
	 *
	 * @param description
	 *            the value for testcase.description
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column testcase.name
	 *
	 * @return the value of testcase.name
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column testcase.name
	 *
	 * @param name
	 *            the value for testcase.name
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column testcase.updatetime
	 *
	 * @return the value of testcase.updatetime
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public String getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column testcase.updatetime
	 *
	 * @param updatetime
	 *            the value for testcase.updatetime
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime == null ? null : updatetime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column testcase.testsuiteid
	 *
	 * @return the value of testcase.testsuiteid
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public Integer getTestsuiteid() {
		return testsuiteid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column testcase.testsuiteid
	 *
	 * @param testsuiteid
	 *            the value for testcase.testsuiteid
	 *
	 * @mbggenerated Wed Feb 24 18:24:56 CST 2016
	 */
	public void setTestsuiteid(Integer testsuiteid) {
		this.testsuiteid = testsuiteid;
	}
}