package  com.ymatou.autorun.datadriver.base.autoresult.database.Bean;

public class TestCaseResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcaseresult.id
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcaseresult.del
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcaseresult.status
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcaseresult.testcaseid
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    private Integer testcaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcaseresult.testsuiteresultid
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    private Integer testsuiteresultid;
    
    
    
    private String createtime;
    
    public String getCreatetime() {
		return createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcaseresult.id
     *
     * @return the value of testcaseresult.id
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcaseresult.id
     *
     * @param id the value for testcaseresult.id
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcaseresult.del
     *
     * @return the value of testcaseresult.del
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcaseresult.del
     *
     * @param del the value for testcaseresult.del
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcaseresult.status
     *
     * @return the value of testcaseresult.status
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcaseresult.status
     *
     * @param status the value for testcaseresult.status
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcaseresult.testcaseid
     *
     * @return the value of testcaseresult.testcaseid
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public Integer getTestcaseid() {
        return testcaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcaseresult.testcaseid
     *
     * @param testcaseid the value for testcaseresult.testcaseid
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public void setTestcaseid(Integer testcaseid) {
        this.testcaseid = testcaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcaseresult.testsuiteresultid
     *
     * @return the value of testcaseresult.testsuiteresultid
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public Integer getTestsuiteresultid() {
        return testsuiteresultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcaseresult.testsuiteresultid
     *
     * @param testsuiteresultid the value for testcaseresult.testsuiteresultid
     *
     * @mbggenerated Wed Feb 24 18:27:59 CST 2016
     */
    public void setTestsuiteresultid(Integer testsuiteresultid) {
        this.testsuiteresultid = testsuiteresultid;
    }
}