package  com.ymatou.autorun.datadriver.base.autoresult.database.Bean;

public class TestPass{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testpass.id
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testpass.createtime
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testpass.del
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testpass.applicationid
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    private Integer applicationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testpass.envid
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    private Integer envid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testpass.id
     *
     * @return the value of testpass.id
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testpass.id
     *
     * @param id the value for testpass.id
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testpass.createtime
     *
     * @return the value of testpass.createtime
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testpass.createtime
     *
     * @param createtime the value for testpass.createtime
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testpass.del
     *
     * @return the value of testpass.del
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testpass.del
     *
     * @param del the value for testpass.del
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testpass.applicationid
     *
     * @return the value of testpass.applicationid
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public Integer getApplicationid() {
        return applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testpass.applicationid
     *
     * @param applicationid the value for testpass.applicationid
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public void setApplicationid(Integer applicationid) {
        this.applicationid = applicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testpass.envid
     *
     * @return the value of testpass.envid
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public Integer getEnvid() {
        return envid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testpass.envid
     *
     * @param envid the value for testpass.envid
     *
     * @mbggenerated Wed Feb 24 18:28:20 CST 2016
     */
    public void setEnvid(Integer envid) {
        this.envid = envid;
    }
}