package  com.ymatou.autorun.datadriver.base.autoresult.database.Bean;

public class TestSuiteResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuiteresult.id
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuiteresult.del
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    private Integer del;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuiteresult.testpassid
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    private Integer testpassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testsuiteresult.testsuiteid
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    private Integer testsuiteid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuiteresult.id
     *
     * @return the value of testsuiteresult.id
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuiteresult.id
     *
     * @param id the value for testsuiteresult.id
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuiteresult.del
     *
     * @return the value of testsuiteresult.del
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuiteresult.del
     *
     * @param del the value for testsuiteresult.del
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuiteresult.testpassid
     *
     * @return the value of testsuiteresult.testpassid
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    public Integer getTestpassid() {
        return testpassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuiteresult.testpassid
     *
     * @param testpassid the value for testsuiteresult.testpassid
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    public void setTestpassid(Integer testpassid) {
        this.testpassid = testpassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testsuiteresult.testsuiteid
     *
     * @return the value of testsuiteresult.testsuiteid
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    public Integer getTestsuiteid() {
        return testsuiteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testsuiteresult.testsuiteid
     *
     * @param testsuiteid the value for testsuiteresult.testsuiteid
     *
     * @mbggenerated Wed Feb 24 18:29:33 CST 2016
     */
    public void setTestsuiteid(Integer testsuiteid) {
        this.testsuiteid = testsuiteid;
    }
}